version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nyc-gbfn-nginx
    ports:
      - "9518:80"  # External port 9518 maps to nginx port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - nyc-gbfn-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service (React/Vite)
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: nyc-gbfn-frontend
    environment:
      - VITE_API_BASE_URL=/api
      - NODE_ENV=production
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - nyc-gbfn-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Service (FastAPI)
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: nyc-gbfn-backend
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL:-http://brahma:8086}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-data-infra-super-secret-auth-token-2025}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-data-infra-org}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-citi-bike-data}
      - LOOKBACK_MINUTES=${LOOKBACK_MINUTES:-15}
    networks:
      - nyc-gbfn-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  nyc-gbfn-network:
    driver: bridge

volumes:
  frontend_node_modules:
